#!/usr/bin/env bash
# Install nginx web server

# Install the Nginx server silently
sudo apt update -y > /dev/null 2>&1
sudo apt install nginx -y >/dev/null 2>&1

# This overwrites the defualt page with my message

echo "Holberton School" > /var/www/html/index.html

# Restart Nginx using the 'service' command instead of 'systemctl'
service nginx restart
